version: "3.9"

services:
  web:
    build: .
    container_name: shegar-web
    command: gunicorn shegar.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    container_name: shegar-db
    environment:
      POSTGRES_DB: shegarlandbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: red17331
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
web:
    depends_on:
      db:
        condition: service_healthy