# Generated by Django 5.1.1 on 2025-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0012_alter_shegarlandform_aanaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='balina_lafa',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
