# Generated by Django 5.1.1 on 2025-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0013_alter_shegarlandform_balina_lafa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='balina_lafa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
