# Generated by Django 5.1.1 on 2025-06-15 17:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0014_alter_shegarlandform_balina_lafa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=32637)),
                ('shegar_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='shegarland.shegarlandform')),
            ],
        ),
    ]
