# Generated by Django 5.1.1 on 2025-06-15 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0015_landfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfeature',
            name='shegar_form',
        ),
        migrations.AddField(
            model_name='landfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landfeature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landfeature',
            name='form',
            field=models.OneToOneField(default=1.9875776397515528e-05, on_delete=django.db.models.deletion.CASCADE, to='shegarland.shegarlandform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='applicant_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
