# Generated by Django 5.1.1 on 2025-06-22 18:40

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0016_remove_landfeature_shegar_form_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kutaamagaalaa', models.CharField(max_length=50, verbose_name='Kutaa Magaalaa')),
                ('Aanaa', models.CharField(max_length=50, verbose_name='Aanaa')),
                ('iddo_adda', models.CharField(blank=True, max_length=30, null=True, verbose_name='Iddoo Addaa')),
                ('lakk_adda', models.IntegerField(blank=True, default=0, null=True)),
                ('gosa_tajajila', models.CharField(max_length=50)),
                ('madda_lafa', models.CharField(max_length=50)),
                ('tajajila_iddo', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('land_use', models.CharField(max_length=100)),
                ('haala_beenya', models.CharField(max_length=20)),
                ('qamaa_qophaef', models.CharField(max_length=50)),
                ('tajajila_qophaef', models.CharField(max_length=50)),
                ('balina_lafa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kan_qophesse', models.CharField(blank=True, default='user', max_length=40, null=True)),
                ('guyya_qophae', models.DateField(verbose_name='Guyyaa Qophaaye')),
                ('guyya_galmae', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Guyyaa Galmaa'e")),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=32637, verbose_name='Geometri')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
