# Generated by Django 5.1.1 on 2025-07-04 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0017_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=32637),
        ),
    ]
