# Generated by Django 5.1.1 on 2025-07-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0018_alter_parcel_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shegarlandform',
            name='Mallattoo',
        ),
        migrations.RemoveField(
            model_name='shegarlandform',
            name='Ragaa_biroo',
        ),
        migrations.RemoveField(
            model_name='shegarlandform',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='shegarlandform',
            name='shapefile',
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='gosa_investimentii',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='lakk_xalayaa_murtoo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='sababa_qophaef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shegarlandform',
            name='sadarka_iddo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='LandFeature',
        ),
    ]
