# Generated by Django 5.1.1 on 2025-07-05 20:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0019_remove_shegarlandform_mallattoo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shegarlandform',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=32637),
        ),
    ]
